# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAnswer', models.CharField(max_length=255, verbose_name='解答')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=255, verbose_name='フラグ')),
                ('point', models.IntegerField(max_length=3, verbose_name='得点')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(max_length=1, verbose_name='レベル')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='title')),
                ('sentence', models.TextField(verbose_name='問題文')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LinuxChallenge.Level', verbose_name='レベル')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('password', models.CharField(max_length=127, verbose_name='パスワード')),
                ('point', models.IntegerField(verbose_name='合計点')),
            ],
        ),
        migrations.AddField(
            model_name='flag',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LinuxChallenge.Question', verbose_name='問題'),
        ),
        migrations.AddField(
            model_name='answer',
            name='flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LinuxChallenge.Flag'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LinuxChallenge.Question', verbose_name='問題'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LinuxChallenge.User', verbose_name='解答者'),
        ),
    ]
