# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinuxChallenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='stage_limit_point',
            field=models.IntegerField(verbose_name='表示制限ポイント'),
        ),
    ]
