# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LinuxChallenge', '0002_auto_20160328_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='お知らせ')),
                ('sentence', models.TextField(verbose_name='内容')),
                ('published_time', models.DateField(default=django.utils.timezone.now, verbose_name='公開された時間')),
            ],
        ),
    ]
