# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LinuxChallenge', '0003_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='published_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='公開された時間'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='タイトル'),
        ),
    ]
